### ISSUE TITLE
function for token F1 score

### ISSUE THREAD

**Issue by Imsovegetable** [jayded/eraserbenchmark#13]
Hello, 
Thanks for the nice work!
I am trying to use the metrics for model evaluation. But I am confused which function in metrics.py is used to calculate token f1 score. 
Could you please let me know which function should I use for token f1 calculation?
Thank you very much!

**Comment by jayded** [comment]
Token scoring for hard-rationales-with-thresholds begins at:
https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L632
And uses https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L168 after projecting any span-level scores to token level scores

Soft token scoring (for comprehensiveness and sufficiency models) begins at:
https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L639
And uses https://github.com/jayded/eraserbenchmark/blob/36467f1662812cbd4fbdd66879946cd7338e08ec/rationale_benchmark/metrics.py#L237
