### ISSUE TITLE
Human Rationales 

### ISSUE THREAD

**Issue by gmihaila** [jayded/eraserbenchmark#16]
Thank you for the great work! I'm having a bit of a hard time to find the human rationales for all datasets. I used the download links and looked thought the files but can't find them. Any help would be greatly appreciated!

**Comment by jayded** [comment]
The data format is documented in https://github.com/jayded/eraserbenchmark/blob/master/rationale_benchmark/utils.py ; specifically the `Evidence` and `Annotation` dataclasses. This file also includes functions for loading the data.

For an example using these functions, take a look at https://github.com/jayded/eraserbenchmark/blob/master/data_exploration.ipynb
