### ISSUE TITLE
Missing Dependency in requirements.txt

### ISSUE THREAD

**Issue by maximilianreimer** [jayded/eraserbenchmark#7]
Hi, 

it seems to me that the `transformers` is missing in the `requirements.txt` since file `rationale_benchmark/models/mlp.py` line 6 requires it (`from transformers import BertForSequenceClassification`).

Cheers

**Comment by jayded** [comment]
Apologies for the delay - notifications were off.
This depends on an older version of the transformers library and isn't validated against newer versions: https://github.com/jayded/eraserbenchmark/blob/master/requirements.txt#L5
`pytorch-transformers==1.1.0`

**Comment by KrnTneja** [comment]
Which Python version are you using? I'm not able to get the dependencies right.
